### ISSUE TITLE
oalab installation

### ISSUE THREAD

**Issue by cokelaer** [openalea/openalea#106]
FYI: I had to clone the _deploy_ package from openalea  github and install it manually  to be able to install oalab. Could be nice to have the deploy package on pypi. There is already another package with that name though.

**Comment by pradal** [comment]
I have successfully installed deploy using pip:

pip install git+https://github.com/openalea/deploy

However, OpenAlea.DeployGui is missing on github.

**Comment by gbaty** [comment]
@pradal : please comment on associated issue ( #110 )
