### ISSUE TITLE
No package openalea.deploygui found in github

### ISSUE THREAD

**Issue by pradal** [openalea/openalea#126]
The package openalea.deploygui is missing on github.
Please add this package on openalea or merge it as an option in deploy.

**Comment by gbaty** [comment]
That is the reason why deploygui is not on github, we need to decide were to put it!
No preferences right now.

**Comment by pradal** [comment]
Deploygui depends on Qt and thus on vpltk.

So, we can first migrate deploygui to openalea.
Then, later on, we would merge deploy and deploygui and install deploygui only when an option [gui] is defined.

**Comment by gbaty** [comment]
Ok for this roadmap! I integrate it soon.

**Comment by pradal** [comment]
Integrate OpenAlea.DeployGui into openalea repository
