### ISSUE TITLE
oalab fails to start in virtualenv 

### ISSUE THREAD

**Issue by cokelaer** [openalea/openalea#216]
Hi,
I've just did a pull on oalab repo, started the application and everything looked fine but then I realised that none of the packages were availabe.

There was an error in the background related to an error in core/src/core/plugins

around line 57 in "iter_groups" function, the site module installed in a virtual env is different from 
the module on the system. One difference is that the method 'getsitepackages' does not exist !

This seems to be known but I'm not sure if this is something you want to fix inside openalea ?

http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

thanks
T.

**Comment by pradal** [comment]
Thanks a lot, Thomas.
We will look at this.

**Comment by revesansparole** [comment]
Had the same bug, welcome to the world of people using virtual environments in python!
But, hey, isn't it supposed to be the norm?
:)

**Comment by revesansparole** [comment]
Found a wrokaround that doesn't use site.py

import pip
installed_packages = pip.get_installed_distributions()

 Hope it helps

**Comment by cokelaer** [comment]
I switched to install mode for now ... cheers

**Comment by pradal** [comment]
Now we use conda for installation.
