### ISSUE TITLE
Error when attempting to run VisuAlea

### ISSUE THREAD

**Issue by carlhamann** [openalea/openalea#226]
I followed this guide: http://virtualplants.github.io/install/install_marsalt.html
until the paragraph 'Download and install Mars-Alt'.

After that I installed:
`sudo apt-get install python-all python-setuptools python-dev debhelper libqt4-dev libqt4-opengl-dev libcgal-dev libboost-python-dev bison flex libqhull-dev libreadline-dev pkg-config freeglut3-dev libann-dev liblapack-dev libblas-dev libmpfr-dev libeigen2-dev`

After not encountering any issue, I used:
`git clone https://github.com/openalea/plantgl.git
cd plantgl
cp options_linux.py options.py`

Since calling `scons -h` worked, I ran `scons`.
Again no error occured. So I called:
`python setup.py develop --user`

Then I installed MTG:
`git clone https://github.com/openalea/mtg.git
python setup.py develop --user`

Now that the installation worked flawlessly, I tried to run VisuAlea, using `visualea`. However I got an error: _ImportError: No module named pygments.token_
Full log: [log_1.txt](https://github.com/openalea/openalea/files/297326/log_1.txt)

Apparently some Python packages were missing, so I used: `sudo apt-get install python-pygments`
After trying to run VisuAlea again, a new error occured: _NameError: global name 'get_interpreter_class' is not defined_
Full log: [log_2.txt](https://github.com/openalea/openalea/files/297330/log_2.txt)

Now I ran these two commands in a Python console:
`from openalea.core.service.ipython import interpreter as get_interpreter
get_interpreter()`
Since this resulted in an error (see [py shell.txt](https://github.com/openalea/openalea/files/297334/py.shell.txt)), I installed IPython: `pip install --user ipython==2.4.1`
However the exact same error occured again (but the traceback is shorter).
Full log: [log.txt](https://github.com/openalea/openalea/files/297337/log.txt)

I am working on Ubuntu 16.04. LTS, 32-bit. My IPython version is 2.4.1

**Comment by revesansparole** [comment]
I repeated your installation on a fresh ubuntu 16.04 32bits virtual machine and I cannot reproduce your error?

Did you actually pip install or apt-get install ipython?

**Comment by pradal** [comment]
Do not succeed to reproduce the error.
