### ISSUE TITLE
Problem to run oalab

### ISSUE THREAD

**Issue by adamavip** [openalea/openalea#230]
Hiiiiii,

I have installed OpenAleaLAB (from https://github.com/openalea/openalea) and all its dependencies(deploy, sconx, ipython, qt4) but when i execute the command "oalab", a window appears and proposes me to choose a lab and when i click on ipython, nothing else occurs. Please do you have any idea about that. Any help would be welcom.

Cheers,

Adama

**Comment by artzet-s** [comment]
Hi Adama,

Have you a message error when you launch "oalab" in a terminal ? 

Maybe you have a problem with your ipython version (I had this installation/version problem recently). Can you try with ipython version 2.4.1 ? Uninstall your current ipython and try this: 

"sudo pip install ipython==2.4.1
sudo pip install "ipython[qtconsole]"

**Comment by adamavip** [comment]
Thanks for the quick answer, i have no error message and i am currently using the version 5.1.0 of ipython, may be it's the source of the problem?

**Comment by artzet-s** [comment]
Yes, 

I think, I just tested and oalab crash with version 5.1.0 of ipython on my ubuntu 16.04

You can try with ipython version 2.4.1 it should works.

**Comment by adamavip** [comment]
Great ! It works well . Thaaaaaaaanks Simon!!!!!
